### ISSUE TITLE
Build initial packages from `git-for-windows-automation`

### ISSUE THREAD

**Issue by dennisameling** [git-for-windows/git-sdk-arm64#3] opened 2023-01-03 07:58 UTC
We'll need to do initial builds of the packages below from `git-for-windows-automation` and push them into the new Pacman repo. **Please use the order of packages below as they sometimes depend on each other**.

- [x] [`mingw-w64-clang-aarch64-openssl`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3890890123)
- [x] [`mingw-w64-clang-aarch64-curl`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3892743233) (my initial version: https://github.com/git-for-windows/git-sdk-arm64/commit/489ef8b0daf61d8894876cc084c8d18b429eba08)
- [x] [`mingw-w64-clang-aarch64-wintoast`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3877787045)
- [x] [`mingw-w64-clang-aarch64-xpdf-tools`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3885250784/jobs/6628889746)
- [x] [`mingw-w64-clang-aarch64-git-credential-manager`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3877865562)
- [x] [`mingw-w64-clang-aarch64-git-lfs`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3887540853)
- [x] [`mingw-w64-clang-aarch64-git-extra`](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3825495631) (done by @dscho ✅)
```

CC @dscho

**Comment by dscho** [comment] 2023-01-03 08:47
Thank you for writing up this list.

Before we go further, I'd like to have an automated way to tear down runners that are no longer needed.

@dennisameling you mentioned that there is a way to run a script on a runner once a job has finished? Could we use that to shut down the machine, maybe with a note (or label) for which we can later query using Azure CLI to identify which Azure resources need to be deleted?

**Comment by dennisameling** [comment] 2023-01-03 09:34
> @dennisameling you mentioned that there is a way to run a script on a runner once a job has finished? Could we use that to shut down the machine, maybe with a note (or label) for which we can later query using Azure CLI to identify which Azure resources need to be deleted?

That would work, but there's an approach I'd like even more I guess: 

- Let the [`gfw-helper-github-app`](https://github.com/git-for-windows/gfw-helper-github-app) listen to the [`workflow_job` webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_job) (`completed` status) 
- Do a call to `https://api.github.com/repos/git-for-windows/git-for-windows-automation/actions/jobs/JOB_ID_HERE` (as you mentioned [here](https://github.com/git-for-windows/git/discussions/4186#discussioncomment-4576493)) to get the `runner_name`
- Call the Azure CLI through GitHub Actions to immediately remove this VM (including all its attached resources) so that you don't pay for the time between "the job has finished" and "we run a query every X mins to find Azure resources that need to be deleted".

WDYT? As a fallback, we could still register a script using the [`ACTIONS_RUNNER_HOOK_JOB_COMPLETED`](https://docs.github.com/en/actions/hosting-your-own-runners/running-scripts-before-or-after-a-job#triggering-the-scripts) environment variable that shuts down the VM _from within the VM itself_. Note that this action won't decommission the VM, but at least will put it in the "Stopped" state to make it clear that this VM is good to be deleted.

**Comment by dscho** [comment] 2023-01-03 21:59
> * Let the [`gfw-helper-github-app`](https://github.com/git-for-windows/gfw-helper-github-app) listen to the [`workflow_job` webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_job) (`completed` status)
> 
> * Do a call to `https://api.github.com/repos/git-for-windows/git-for-windows-automation/actions/jobs/JOB_ID_HERE` (as you mentioned [here](https://github.com/git-for-windows/git/discussions/4186#discussioncomment-4576493)) to get the `runner_name`
> 
> * Call the Azure CLI through GitHub Actions to immediately remove this VM (including all its attached resources) so that you don't pay for the time between "the job has finished" and "we run a query every X mins to find Azure resources that need to be deleted".

I like that approach.

We might not even need the extra REST call to determine the runner name: I only looked at the `check_run.completed` webhook event because (as I found out today) I had failed to check the box so that `workflow_job` events would be delivered to the GitForWindowsHelper App... I corrected that mistake, and the next time we build a package, I will have a look at that `workflow_job` event payload.

> As a fallback, we could still register a script using the [`ACTIONS_RUNNER_HOOK_JOB_COMPLETED`](https://docs.github.com/en/actions/hosting-your-own-runners/running-scripts-before-or-after-a-job#triggering-the-scripts) environment variable that shuts down the VM _from within the VM itself_. Note that this action won't decommission the VM, but at least will put it in the "Stopped" state to make it clear that this VM is good to be deleted.

I implemented that in git-for-windows/git-for-windows-automation@8d6ab88

> mingw-w64-clang-aarch64-wintoast

FWIW this will be a bit more of a challenge than it looks, as it uses MSVC to build the executable (and we haven't added automation to install a community version of Visual Studio yet). On the other hand, we _might_ be able to build this package on hosted runners (because Visual Studio _is_ installed there, maybe even with the bits required to build ARM64 binaries).

> mingw-w64-clang-aarch64-git-credential-manager
> mingw-w64-clang-aarch64-git-lfs

These two are "interesting" in that we're not really building them. We simply download the portable versions, consuming what the respective projects offer.

As far as [Git Credential Manager](https://github.com/GitCredentialManager/git-credential-manager/releases) is concerned, that might be actually easy: we consume the x86 version there, even for the amd64 package. We could do the very same for arm64, too.

[Git LFS](https://github.com/git-lfs/git-lfs/releases/tag/v3.3.0), on the other hand, _does_ provide an arm64 version (thanks to you, @dennisameling).

The `xpdf-tools`, `openssl` and `curl` packages should work comparatively easily.

**Comment by dennisameling** [comment] 2023-01-03 22:44
> FWIW this will be a bit more of a challenge than it looks, as it uses MSVC to build the executable (and we haven't added automation to install a community version of Visual Studio yet). On the other hand, we might be able to build this package on hosted runners (because Visual Studio is installed there, maybe even with the bits required to build ARM64 binaries).

The hosted runners _do_ contain the bits that are needed to cross-compile things from x64 to arm64. I used it in the past for other projects. It's just a matter of specifying `/p:Platform=ARM64`, [which we already do](https://github.com/git-for-windows/build-extra/blob/ebe6c944c573ee4d8900f0e015365468606c9e1e/mingw-w64-wintoast/PKGBUILD#L40). MSBuild will take care of the rest 😄

**Comment by dscho** [comment] 2023-01-04 21:54
> The hosted runners _do_ contain the MSVC bits that are needed to cross-compile things from x64 to arm64.

So we'll have to patch `build-and-deploy.yml` to allow for running in MINGW64 mode, but building in CLANGARM64 mode except that we're letting MSVC do the job? That might get rather fiddly.

I briefly tried to compile `wintoast.exe` using GCC (assuming that the headers would be the same as for `clang`), and unfortunately the necessary system headers defining e.g. `ToastDismissalReason` simply aren't available.

The least fragile option might be to special-case `wintoast` and add support to our self-hosted runner workflow to allow for installing Visual Studio. [Here](https://github.com/dotnet/Comet/blob/f09bb4032098c90cf53cd8d60e184fc59b399731/build/install-vs.ps1#L21) is an example that does that in an Azure Pipeline, but it does not install the Visual C workload, that would probably look like `--add Microsoft.VisualStudio.Workload.VCTools` or [`--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended`](https://github.com/PointCloudLibrary/pcl/blob/319e433fa35c7deeee4717b08734b7223473b265/.dev/docker/windows/Dockerfile#L32).

**Comment by dscho** [comment] 2023-01-04 22:20
> > The hosted runners _do_ contain the MSVC bits that are needed to cross-compile things from x64 to arm64.
> 
> So we'll have to patch `build-and-deploy.yml` to allow for running in MINGW64 mode, but building in CLANGARM64 mode except that we're letting MSVC do the job? That might get rather fiddly.

Hmm. I just tried `MINGW_ARCH=clangarm64 makepkg-mingw` locally, and after installing the required build tools component in Visual Studio Installer, that worked. So maybe it is not all that fiddly at all. Maybe all that is needed is to patch [this line](https://github.com/git-for-windows/git-for-windows-automation/blob/6b1fdd918407fa40c6c43f7a82c88e742a7ec85c/.github/workflows/build-and-deploy.yml#L244) to echo "mingw32 mingw64 clangarm64" in case we're building `wintoast`. Something like:

```sh
          MINGW_ARCHS_TO_BUILD=$(
                    case "$ARCHITECTURE,$PACKAGE_TO_BUILD" in
                    aarch64,*) echo "clangarm64";;
                    *,mingw-w64-wintoast) echo "mingw32 mingw64 clangarm64";; # We're (cross-)compiling via Visual Studio
                    *) echo "mingw32 mingw64";;
                    esac
          )
```

And for the initial ARM64 deployment (since we want to avoid rebuilding the x86/amd64 versions), we could trigger that deployment from a branch that temporarily deletes the "mingw32 mingw64" part.

**Comment by dennisameling** [comment] 2023-01-05 12:06
Sounds great to me! Thanks!

**Comment by dscho** [comment] 2023-01-10 17:01
Current state: trying [to build xpdf-tools](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3885250784/jobs/6628889746), but sadly it seems that this agent got tar-pitted somehow and now clones at 55kB/sec... ☹️

**Comment by dscho** [comment] 2023-01-10 19:28
> Current state: trying [to build xpdf-tools](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3885250784/jobs/6628889746), but sadly it seems that this agent got tar-pitted somehow and now clones at 55kB/sec... ☹️

But it eventually picked up speed again and succeeded!

**Comment by dscho** [comment] 2023-01-10 22:00
> Before we go further, I'd like to have an automated way to tear down runners that are no longer needed.

With https://github.com/git-for-windows/git-for-windows-automation/pull/11 (merged) and with https://github.com/git-for-windows/gfw-helper-github-app/pull/20 (pending merge), I think we'll have that in place.

**Comment by dscho** [comment] 2023-01-11 08:14
> * `mingw-w64-clang-aarch64-openssl` (my initial version: [621d915](https://github.com/git-for-windows/git-sdk-arm64/commit/621d9157a5cc76416d8dd333f38271267b52baf2))

After merging git-for-windows/gfw-helper-github-app#20, I triggered [the aarch mingw-w64-openssl build](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3890890123). If all goes well, the automation will automatically spin up and tear down the self-hosted runner.🤞

**Comment by dscho** [comment] 2023-01-11 08:15
The [build to spin up the runner](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3890890720) was triggered automatically. So that part works as intended!

**Comment by dscho** [comment] 2023-01-11 08:21
The runner was spun up successfully and started building the package.

**Comment by dscho** [comment] 2023-01-11 08:24
Also, [the `build_aarch64` check run is correctly attached to the targeted commit in `MINGW-packages`](https://github.com/git-for-windows/MINGW-packages/runs/10572171905) (with the link correctly updated to point to the actual workflow run, thanks to @rimrul's excellent work!).

**Comment by dscho** [comment] 2023-01-11 08:41
It's _so_ close to finishing, but I'll have to step away from this project for a while. Will update later.

**Comment by dennisameling** [comment] 2023-01-11 10:34
Thank you so much! Super exciting. Has someone already started porting over [git-artifacts.yml](https://github.com/git-for-windows/git/blob/main/.github/workflows/git-artifacts.yml) to `git-for-windows-automation`? I remember you shared a desire for that in some thread and it makes a ton of sense in my head too. If not, I can probably start working on that some time next week and also turn it into a "dynamic matrix" like you already built into some other workflows.

**Comment by dscho** [comment] 2023-01-11 12:21
> Super exciting.

Yep, especially since the [workflow to delete the runner was triggered automatically, too](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3891095986)!

> Has someone already started porting over [git-artifacts.yml](https://github.com/git-for-windows/git/blob/main/.github/workflows/git-artifacts.yml) to `git-for-windows-automation`?

Not that I am aware of.

> I remember you shared a desire for that in some thread and it makes a ton of sense in my head too. If not, I can probably start working on that some time next week and also turn it into a "dynamic matrix" like you already built into some other workflows.

That would be awesome!

**Comment by dscho** [comment] 2023-01-11 12:23
> `mingw-w64-clang-aarch64-curl` (my initial version: [489ef8b](https://github.com/git-for-windows/git-sdk-arm64/commit/489ef8b0daf61d8894876cc084c8d18b429eba08))

Let's [try building this, too](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3892743233).

**Comment by dscho** [comment] 2023-01-11 13:24
> > `mingw-w64-clang-aarch64-curl` (my initial version: [489ef8b](https://github.com/git-for-windows/git-sdk-arm64/commit/489ef8b0daf61d8894876cc084c8d18b429eba08))
> 
> Let's [try building this, too](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/3892743233).

Worked! With this, I declare this ticket done! 🎉

**Closed by dscho** 2023-01-11 13:24 UTC

**Comment by dscho** [comment] 2023-01-23 16:46
> > Has someone already started porting over [git-artifacts.yml](https://github.com/git-for-windows/git/blob/main/.github/workflows/git-artifacts.yml) to `git-for-windows-automation`?
> 
> Not that I am aware of.

@dennisameling I should have thought a little harder. A _variation_ of `git-artifacts` is actually used in https://github.com/microsoft/git/blob/v2.39.1.vfs.0.0/.github/workflows/build-git-installers.yml#L49-L299 to build the releases over in `microsoft/git`; We might want to take some inspiration from that workflow.

**Comment by dennisameling** [comment] 2023-01-23 18:52
Thanks for sharing! I think that's quite close to [the approach I took in this PR](https://github.com/git-for-windows/git-for-windows-automation/pull/22).
